config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :foods, only: [:index, :show] do
    collection do
      get 'search'
    end
  end

  # 英語のトップページ
  get 'english', to: 'english_pages#home', as: 'english_home'
  # 英語の foods ルーティング
  resources :english_foods, only: [:index, :show] do
    collection do
      get 'search'
    end
  end
end

app/models/english_food.rb
class EnglishFood < ApplicationRecord
  validates :name, presence: true
  validates :prefecture, presence: true
  validates :history, presence: true
  validates :image_url, presence: true
  validates :detail_url, presence: true, uniqueness: true

  def self.search(name_keyword, prefecture_keyword)
    foods = EnglishFood.all
    if name_keyword.present?
      foods = foods.where('LOWER(name) LIKE ?', "%#{name_keyword.downcase}%")
    end
    if prefecture_keyword.present?
      foods = foods.where('LOWER(prefecture) LIKE ?', "%#{prefecture_keyword.downcase}%")
    end
    foods
  end

  def image_filename
  filename = File.basename(URI.parse(image_url).path, ".*")
  filename.gsub!('-1', '') if filename.include?('-1') 
  filename
  end
end

app/controllers/english_foods_controller.rb
class EnglishFoodsController < ApplicationController
  def index
    prefecture_order = EnglishPrefecture.all.map(&:name)

    if params[:prefecture].present? && params[:prefecture] != "All"
      selected_prefecture = params[:prefecture]
      @foods = EnglishFood.where(prefecture: selected_prefecture)
      @foods_by_prefecture = { selected_prefecture => @foods }
    else
      @foods = EnglishFood.all
      foods_grouped_by_prefecture = @foods.group_by(&:prefecture)
      @foods_by_prefecture = prefecture_order.each_with_object({}) do |prefecture, hash|
        hash[prefecture] = foods_grouped_by_prefecture[prefecture] || []
      end
    end
  end

  def show
    @food = EnglishFood.find(params[:id])
    extracted_name = @food.food_name.split(/[／(（]/).first
    encoded_name = URI.encode_www_form_component(extracted_name)
    encoded_prefecture = URI.encode_www_form_component(@food.prefecture)

    @kyodoryouri_info = {
      name: @food.name,
      prefecture: @food.prefecture,
      history: @food.history,
      image_url: @food.image_url,
      image_source: @food.image_credit
    }
    base_tabelog_url = "https://tabelog.com/rstLst/?vs=1&sa=&sk=#{encoded_name}&sw=#{encoded_name}&trailing_slash=true&srchTg=2"
    translated_base_url = URI.encode_www_form_component(base_tabelog_url)
    @tabelog_url = "https://translate.google.com/translate?hl=en&sl=ja&u=#{translated_base_url}&prev=search&pto=aue"
    
    @instagram_url = "https://www.instagram.com/explore/tags/#{encoded_name}"

    base_cookpad_url = "https://cookpad.com/search/#{encoded_name}"
    @cookpad_url = "https://translate.google.com/translate?hl=en&sl=ja&u=#{base_cookpad_url}&prev=search&pto=aue"
  end

  def search
    @prefectures = EnglishPrefecture.all
    # 最初に選択された都道府県で絞り込み
    if params[:prefecture].present? && params[:prefecture] != "すべて"
      @foods = EnglishFood.where('LOWER(prefecture) = ?', params[:prefecture].downcase)
    else
      @foods = EnglishFood.all
    end

    # 料理名でさらにフィルタリング
    if params[:name_keyword].present?
      keyword = "%#{params[:name_keyword]}%"
      @foods = @foods.where('LOWER(name) LIKE ?', keyword)
    end

    # 都道府県ごとにグループ化
    @foods_by_prefecture = @prefectures.each_with_object({}) do |prefecture, hash|
      hash[prefecture.name] = @foods.select { |food| food.prefecture == prefecture.name }
    end
  end
end

app/helpers/english_foods_helper.rb
module EnglishFoodsHelper
end

app/views/english_foods/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>食品一覧</title>
  <%= stylesheet_link_tag 'style' %>
</head>
<body>
  <header class="common-header">
    <nav>
      <ul>
        <li><a href="/">Home</a></li>
      </ul>
    </nav>
  </header>
  <div class="filter-container">
    <%= form_with(url: english_foods_path, method: :get, local: true) do %>
      <label for="prefecture">Prefecture:</label>
      <select name="prefecture" id="prefecture">
        <option value="All">All</option>
        <% EnglishPrefecture.all.each do |prefecture| %>
          <option value="<%= prefecture.name %>" <%= 'selected' if params[:prefecture] == prefecture.name %>><%= prefecture.name %></option>
        <% end %>
      </select>
      <%= submit_tag "表示" %>
    <% end %>
  </div>

  <div class="prefecture-container">
    <% @foods_by_prefecture.each do |prefecture, foods| %>
      <section id="<%= prefecture.parameterize %>" class="prefecture-section">
        <h2><%= prefecture %></h2>
        <div class="food-list">
          <% foods.each do |food| %>
            <div class="food-item">
              <h3><%= link_to food.name, english_food_path(food) %></h3>
              <%= image_tag food.image_url, alt: food.name, class: "food-image" if food.image_url.present? %>
            </div>
          <% end %>
        </div>
      </section>
    <% end %>
  </div>
</body>
</html>

app/views/english_foods/search.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Search Results</title>
  <%= stylesheet_link_tag 'style' %>
</head>
<body>
  <header class="common-header">
    <nav>
      <ul>
        <li><a href="/">Home</a></li>
        <li><a href="/english_foods">list</a></li>
      </ul>
    </nav>
  </header>

  <div class="search-container">
    <%= form_with(url: search_english_foods_path, local: true, method: :get, class: "search-search-form") do |form| %>
      <%= form.text_field :name_keyword, placeholder: "Search for Regional Cuisine", class: "search-search-input" %>
        <%= form.label :prefecture, "Prefecture:" %>
        <%= form.select :prefecture, options_from_collection_for_select(@prefectures, :name, :name, selected: params[:prefecture]), { include_blank: "ALL" }, class: "search-search-input" %>
      <%= form.submit "Search", class: "search-search-btn" %>
    <% end %>
  </div>

  <div class="search-contents">
  <% @foods.each do |food| %>
    <div class="search-food-item">
      <%= link_to "#{food.name}【#{food.prefecture}】", english_food_path(food) %>
      <%= image_tag food.image_url, alt: food.name, class: "search-food-image" if food.image_url.present? %>
    </div>
  <% end %>
  </div>
</body>
</html>

app/views/english_foods/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>郷土料理詳細</title>
  <%= stylesheet_link_tag 'style', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <header class="common-header">
    <nav>
      <ul>
        <li><%= link_to 'Cuisine List', english_foods_path %></li>
        <li><%= link_to 'home', english_home_path %></li>
      </ul>
    </nav>
  </header>
  <div class="show-container">
    <div class="show-top">
      <div class="show-image">
        <%= image_tag @kyodoryouri_info[:image_url] if @kyodoryouri_info[:image_url].present? %>
        <p><%= @kyodoryouri_info[:image_source] %></p>
      </div>
      <div class="show-details">
        <h1><%= @kyodoryouri_info[:name] %></h1>
        <p><strong>Prefecture:</strong> <%= @kyodoryouri_info[:prefecture] %></p>
        <div class="show-links">
          <div class="link-item">
            <span class="link-text">    Dine Out！</span>
            <%= link_to "Search on Tabelog", @tabelog_url, class: "btn btn-tabelog", target: "_blank" %>
          </div>
          <div class="link-item">
            <span class="link-text">Cook at Home！</span>
            <%= link_to "Search on Cookpad", @cookpad_url, class: "btn btn-cookpad", target: "_blank" %>
          </div>
          <div class="link-item">
            <span class="link-text">View Photos！</span>
            <%= link_to "Search on Instagram", @instagram_url, class: "btn btn-instagram", target: "_blank" %>
          </div>
        </div>
      </div>
    </div>
    <div class="show-bottom">
      <h2>History/origin/related events</h2>
      <p><%= @kyodoryouri_info[:history] %></p>
    </div>
  </div>
</body>
</html>