config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :foods, only: [:index, :show] do
    collection do
      get 'search'
    end
  end

  # 英語のトップページ
  get 'english', to: 'english_pages#home', as: 'english_home'
  # 英語の foods ルーティング
  resources :english_foods, only: [:index, :show] do
    collection do
      get 'search'
    end
  end
end

app/models/food.rb
class Food < ApplicationRecord
  validates :name, presence: true
  validates :prefecture, presence: true
  validates :history, presence: true
  validates :image_url, presence: true
  validates :detail_url, presence: true, uniqueness: true

  def self.search(name_keyword, prefecture_keyword)
    foods = Food.all
    if name_keyword.present?
      foods = foods.where('name LIKE ?', "%#{name_keyword}%")
    end
    if prefecture_keyword.present?
      foods = foods.where('prefecture LIKE ?', "%#{prefecture_keyword}%")
    end
    foods
  end

  def image_filename
    # ファイル名を抽出し、拡張子を除く
    filename = File.basename(URI.parse(image_url).path, ".*")
    # ファイル名に"-1"が含まれていた場合は除去
    filename.gsub!('-1', '') if filename.include?('-1')
    filename
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    prefecture_order = Prefecture.all.map(&:name)

    if params[:prefecture].present? && params[:prefecture] != "すべて"
      selected_prefecture = params[:prefecture]
      @foods = Food.where(prefecture: selected_prefecture)
      @foods_by_prefecture = { selected_prefecture => @foods }
    else
      @foods = Food.all
      foods_grouped_by_prefecture = @foods.group_by(&:prefecture)
      @foods_by_prefecture = prefecture_order.each_with_object({}) do |prefecture, hash|
        hash[prefecture] = foods_grouped_by_prefecture[prefecture] || []
      end
    end
  end

  def show
    @food = Food.find(params[:id])
    extracted_name = @food.name.split(/[／(（]/).first
    encoded_name = URI.encode_www_form_component(extracted_name)
    encoded_prefecture = URI.encode_www_form_component(@food.prefecture)

    @kyodoryouri_info = {
      name: @food.name,
      prefecture: @food.prefecture,
      history: @food.history,
      image_url: @food.image_url,
      image_source: @food.image_credit
    }
      @tabelog_url = "https://tabelog.com/rstLst/?vs=1&sa=&sk=#{encoded_name}&sw=#{encoded_name}&trailing_slash=true&srchTg=2"
      @instagram_url = "https://www.instagram.com/explore/tags/#{encoded_name}"
      @cookpad_url = "https://cookpad.com/search/#{encoded_name}"
    end

  def search
    @prefectures = Prefecture.all
    # 最初に選択された都道府県で絞り込み
    if params[:prefecture].present? && params[:prefecture] != "すべて"
      @foods = Food.where(prefecture: params[:prefecture])
    else
      @foods = Food.all
    end

    # 料理名でさらにフィルタリング
    if params[:name_keyword].present?
      keyword = "%#{params[:name_keyword]}%"
      @foods = @foods.where('name LIKE ?', keyword)
    end

    # 都道府県ごとにグループ化
    @foods_by_prefecture = @prefectures.each_with_object({}) do |prefecture, hash|
      hash[prefecture.name] = @foods.select { |food| food.prefecture == prefecture.name }
    end
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>食品一覧</title>
  <%= stylesheet_link_tag 'style' %>
</head>
<body>
  <header class="common-header">
    <nav>
      <ul>
        <li><a href="/">Home</a></li>
      </ul>
    </nav>
  </header>
  <div class="filter-container">
    <%= form_with(url: foods_path, method: :get, local: true) do %>
      <label for="prefecture">都道府県:</label>
      <select name="prefecture" id="prefecture">
        <option value="すべて">すべて</option>
        <% Prefecture.all.each do |prefecture| %>
          <option value="<%= prefecture.name %>" <%= 'selected' if params[:prefecture] == prefecture.name %>><%= prefecture.name %></option>
        <% end %>
      </select>
      <%= submit_tag "表示" %>
    <% end %>
  </div>

  <div class="prefecture-container">
    <% @foods_by_prefecture.each do |prefecture, foods| %>
      <section id="<%= prefecture.parameterize %>" class="prefecture-section">
        <h2><%= prefecture %></h2>
        <div class="food-list">
          <% foods.each do |food| %>
            <div class="food-item">
              <h3><%= link_to food.name, food_path(food) %></h3>
              <%= image_tag food.image_url, alt: food.name, class: "food-image" if food.image_url.present? %>
            </div>
          <% end %>
        </div>
      </section>
    <% end %>
  </div>
</body>
</html>

app/views/foods/search.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>検索結果</title>
  <%= stylesheet_link_tag 'style' %>
</head>
<body>
  <header class="common-header">
    <nav>
      <ul>
        <li><a href="/">Home</a></li>
        <li><a href="/foods">郷土料理一覧</a></li>
      </ul>
    </nav>
  </header>

  <div class="search-container">
    <%= form_with(url: search_foods_path, local: true, method: :get, class: "search-search-form") do |form| %>
      <%= form.text_field :name_keyword, placeholder: "郷土料理を検索する", class: "search-search-input" %>
        <%= form.label :prefecture, "都道府県:" %>
        <%= form.select :prefecture, options_from_collection_for_select(@prefectures, :name, :name, selected: params[:prefecture]), { include_blank: "すべて" }, class: "search-search-input" %>
      <%= form.submit "検索", class: "search-search-btn" %>
    <% end %>
  </div>

  <div class="search-contents">
  <% @foods.each do |food| %>
    <div class="search-food-item">
      <%= link_to "#{food.name}【#{food.prefecture}】", food_path(food) %>
      <%= image_tag food.image_url, alt: food.name, class: "search-food-image" if food.image_url.present? %>
    </div>
  <% end %>
  </div>
</body>
</html>

app/views/foods/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>郷土料理詳細</title>
  <%= stylesheet_link_tag 'style', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <header class="common-header">
    <nav>
      <ul>
        <li><%= link_to '郷土料理一覧', foods_path %></li>
        <li><%= link_to 'ホーム', root_path %></li>
      </ul>
    </nav>
  </header>
  <div class="show-container">
    <div class="show-top">
      <div class="show-image">
        <%= image_tag @kyodoryouri_info[:image_url] if @kyodoryouri_info[:image_url].present? %>
        <p><%= @kyodoryouri_info[:image_source] %></p>
      </div>
      <div class="show-details">
        <h1><%= @kyodoryouri_info[:name] %></h1>
        <p><strong>県名:</strong> <%= @kyodoryouri_info[:prefecture] %></p>
        <div class="show-links">
          <div class="link-item">
            <span class="link-text">    お店で食べたい！</span>
            <%= link_to "食べログで検索する", @tabelog_url, class: "btn btn-tabelog", target: "_blank" %>
          </div>
          <div class="link-item">
            <span class="link-text">おうちでつくりたい！</span>
            <%= link_to "Cookpadで検索する", @cookpad_url, class: "btn btn-cookpad", target: "_blank" %>
          </div>
          <div class="link-item">
            <span class="link-text">写真をみたい！</span>
            <%= link_to "Instagramで検索する", @instagram_url, class: "btn btn-instagram", target: "_blank" %>
          </div>
        </div>
      </div>
    </div>
    <div class="show-bottom">
      <h2>歴史・由来・関連行事</h2>
      <p><%= @kyodoryouri_info[:history] %></p>
    </div>
  </div>
</body>
</html>